"""added unique constraint ensuring a player only appears once per match for participants

Revision ID: 0da5e439069d
Revises: 3d4e3d635bca
Create Date: 2026-03-03 09:11:03.194931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0da5e439069d'
down_revision: Union[str, Sequence[str], None] = '3d4e3d635bca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_participant_match_player', 'participants', ['match_id', 'player_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_participant_match_player', 'participants', type_='unique')
    # ### end Alembic commands ###
