"""initial tables

Revision ID: 3d4e3d635bca
Revises: 
Create Date: 2026-03-03 07:50:50.161033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d4e3d635bca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(), nullable=False),
    sa.Column('patch', sa.String(), nullable=True),
    sa.Column('queue_id', sa.Integer(), nullable=True),
    sa.Column('game_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_length', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_match_id'), 'matches', ['match_id'], unique=True)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('puuid', sa.String(), nullable=False),
    sa.Column('game_name', sa.String(), nullable=True),
    sa.Column('tag_line', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_puuid'), 'players', ['puuid'], unique=True)
    op.create_table('participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('placement', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('gold_left', sa.Integer(), nullable=True),
    sa.Column('last_round', sa.Integer(), nullable=True),
    sa.Column('total_damage', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_match_id'), 'participants', ['match_id'], unique=False)
    op.create_index(op.f('ix_participants_player_id'), 'participants', ['player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_participants_player_id'), table_name='participants')
    op.drop_index(op.f('ix_participants_match_id'), table_name='participants')
    op.drop_table('participants')
    op.drop_index(op.f('ix_players_puuid'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_matches_match_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
